### ISSUE TITLE
Possible to publish to Github Packages?

### ISSUE THREAD

**Issue by camdub** [atlassian/changesets#287]
## Affected Packages

CLI publish command

## Problem

It appears that the current publish command always assumes the public registry. If there is a way to do this with the current version of `changesets` I haven't been able to figure it out.

## Proposed solution

Update publish command to check `publishConfig.registry` before publishing to the public registry.

**Comment by aussiegeek** [comment]
I am publishing private packages to GitHub using changesets.

I've added this config to the individual package:

```
"publishConfig": {
    "registry": "https://npm.pkg.github.com"
},
"repository": {
    "type": "git",
    "url": "ssh://git@github.com/user/repo.git",
    "directory": "packages/package-name"
}
```

Because there are multiple packages published from the one repo, you need the repository key to point back at GitHub (see https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages#publishing-multiple-packages-to-the-same-repository)

**Comment by ibeyene** [comment]
getting ```🦋  error an error occurred while running `npm profile get`: EAUTHIP```

**Comment by Noviny** [comment]
Npm profile get, my nemesis rears its head again. I’m leaving this issue open till we document this, but @ibeyene could you raise a second issue with a few more details on how you got this error?

Would love to see the output of npm whoami as well.

**Comment by ibeyene** [comment]
The release has failed: https://github.com/atlassian/changesets/runs/488998801?check_suite_focus=true#step:5:20

**Comment by tometo-dev** [comment]
Hi @aussiegeek,
Possible to share how you were able to publish packages to github using changesets.
Everytime I try, it gives the following error:
```
🦋  error ENEEDAUTH This command requires you to be logged in to https://npm.pkg.github.com/ 
🦋  error You need to authorize this machine using `npm adduser`
🦋  error npm ERR! code ENEEDAUTH
🦋  error npm ERR! need auth This command requires you to be logged in to https://npm.pkg.github.com/
🦋  error npm ERR! need auth You need to authorize this machine using `npm adduser`
🦋  error {
🦋  error   "error": {
🦋  error     "code": "ENEEDAUTH",
🦋  error     "summary": "This command requires you to be logged in to https://npm.pkg.github.com/",
🦋  error     "detail": "You need to authorize this machine using `npm adduser`"
🦋  error   }
🦋  error }
```

Snippet from `release.yml` file:
```yaml
- name: Create Release Pull Request or Publish
   uses: changesets/action@v1
   with:
       publish: yarn changeset:release
       commit: "chore: version packages"
       title: "chore: version packages"
    env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Thanks

**Comment by lmacedotzt** [comment]
@tometo-dev I don't know if you were able to solve it, but what I did was before the `Create Release Pull Request or Publish` step, I created the `.npmrc` with Github registry info like this:

```yml
- name: Creating .npmrc
  run: |
    cat << EOF > "$HOME/.npmrc"
      //npm.pkg.github.com/:_authToken=$NPM_TOKEN
    EOF
  env:
    NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

It would be great to pass the registry as an option or just pick it from the package.json if it exists.

**Comment by tometo-dev** [comment]
@lmacedotzt Thanks for the reply. I was able to solve it by doing something similar.

**Comment by jjenzz** [comment]
if it helps anyone, i used the following for this:

```yaml
- name: 🏗 Setup Node
  uses: actions/setup-node@v3
  with:
    registry-url: 'https://npm.pkg.github.com'

- name: 🚀 Create and publish versions
  uses: changesets/action@v1
  with:
    publish: pnpm release
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

the `NODE_AUTH_TOKEN` is what `actions/setup-node@v3` looks for.
