### ISSUE TITLE
Document @changesets/cli integration with Azure DevOps release pipelines

### ISSUE THREAD

**Issue by NateRadebaugh** [atlassian/changesets#294]
## Affected Packages

`@changesets/cli`

## Problem

My company doesn't use Github, so Github actions won't work for me. However, we use Azure DevOps for CI, so it'd be great to have an action/job/task or even a script to use in that environment for provide the same or similar functionality for our build/release environments.

## Proposed solution

It'd be good to update the "CI" section of the docs to include the bare minimum manual steps or scripts required to work with the `@changesets/cli` nicely.

Ideally the Github action would be ported to Azure DevOps to update PRs, leave comments, etc. if that's possible in that world.

**Comment by takrishna** [comment]
Has anybody succeeded in consuming changesets on Azure DevOPs (ADO) pipeline ?

**Comment by tlqvst** [comment]
Also interested in this.
Publishing changesets is easy enough with a pipeline to just run the commands, but what we need is what the Github bot does, calculating the final release based on all committed changesets and creating that PR. Is it specifically written for Github, or can it do the same things by executing commands? Can't find any info on it.

**Comment by pats** [comment]
Sounds very interesting. Any ideas how to get it done?

**Comment by orenmizr** [comment]
has anyone managed to automate it for azure devops ?

**Comment by orenmizr** [comment]
i am also trying to get azure devops intergration. i must ask: i have pnpm + turborepo. and **i cannot make changeset work automatically**. how can it create changesets and bump without a developer manually doing something ? worked on package1, will bump it according the conventional commit "feat: added something"

**Comment by eimerreis** [comment]
@orenmizr I think you could achieve this by extending the existing changelog generator like `changelog-git` or maybe have a look at the (changelog generator of react-select)[https://github.com/JedWatson/react-select/blob/master/.changeset/getChangelogEntry.js

**Comment by orenmizr** [comment]
thanks. i did no this was possible. i have looked in dozens of repos that have turborepo installed and i did not find any of them with a release scripts or a way to track versions fully automatic. starting to think i'm missing something. 
changeset asks you which repo do you want to mark - i thought the whole point was to track which repos were touched and inject to a changeset. have a manual process does not work in real world - you cannot leave it to the developers. imo

**Comment by orenmizr** [comment]
working with azure devops:
anyone here is aware of a way to keep changesets and still be able to fail a pr if a developer did not add a changeset for his code. ( "since-master" will not work because it sees others's stored changesets)

**Comment by eimerreis** [comment]
@orenmizr maybe you could write a small PowerShell script and add it as a build validation pipeline which basically checks for the existence of changeset files between two commits, via `git log`?

**Comment by orenmizr** [comment]
ended up writing a script that for each PR see if the the developer has created some *.MD file in the changeset directory - "has he described the changes of his PR". 

it allowed me to bypass the issues that when aggregating change sets and bumping till release makes the since-master not useful.

**Comment by toinfinityandbeyond** [comment]
Hi all, I'm trying to make `npx changeset publish` inside an azure devops pipeline. All my packages are correctly published, but tags are not pushed to the branch. Anyone knows why?

**Comment by wolfie82** [comment]
> Hi all, I'm trying to make `npx changeset publish` inside an azure devops pipeline. All my packages are correctly published, but tags are not pushed to the branch. Anyone knows why?

You likely need to do something like the below.

```yaml
steps:
  - task: Bash@3
    name: version
    displayName: 'Version'
    env:
      GIT_TOKEN: $(System.AccessToken)
      CI: true
    inputs:
      targetType: 'inline'
      script: |
        set -x

        # Checkout the right branch
        git fetch --all
        git switch $(basename $(Build.SourceBranch))
        
        # Install dependencies
        npm ci
        
        # Run changeset and release
        npx changeset status
        if [ $? -eq 0 ]; then
          npx changeset version
          git add .changeset
          npx changeset publish
          git -c http.extraheader="AUTHORIZATION: bearer $GIT_TOKEN" push
          git -c http.extraheader="AUTHORIZATION: bearer $GIT_TOKEN" push origin --tags
        fi
```
