### ISSUE TITLE
Allow customizing or omitting the 'v' git tag prefix for single package repositories

### ISSUE THREAD

**Issue by jorenbroekema** [atlassian/changesets#386]
## Affected Packages

@changesets/cli

## Problem

`yarn changeset publish` generates the wrong tag. It generated `v0.1.0` instead of the expected `@web/test-runner-core@0.1.0`. 

I am running `@changesets/cli@2.8.0`. Here's the repo where it runs in the CI: https://github.com/modernweb-dev/web/runs/742888839 --> Release to NPM step

Here's my workflow yml:
```yml 
name: Release

on:
  push:
    branches:
      - master
    paths:
      - '.changeset/*.md'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0


      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn

      - name: Changeset version
        run: yarn changeset version

      - name: Commit version updates
        run: |
          git config --local user.email "john.doe@gmail.com"
          git config --local user.name "Joren Broekema"
      - run: git add .
      - run: "git commit -m 'chore: release new versions'"

      - name: Release to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn changeset publish

      - name: Push commits and tags to GitHub
        run: git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY} --follow-tags
```

For contrast, here's where I ran it as an experiment in a different repo, and there it worked correctly:
https://github.com/jorenbroekema/modern-monorepo-test/runs/704325907 --> Release to NPM step. I double checked and it ran `@changesets/cli@2.7.2`. 

Workflow yml:
```yml
name: Release

on:
  push:
    branches:
      - master
    paths:
      - '.changeset/*.md'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0


      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn

      - name: Changeset version
        run: yarn changeset version

      - name: Commit version updates
        run: |
          git config --local user.email "john.doe@gmail.com"
          git config --local user.name "Joren Broekema"
      - run: git add .
      - run: "git commit -m 'chore: make release'"

      - name: Release to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn changeset publish

      - name: Push commits and tags to GitHub
        run: git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY} --follow-tags
```

My suspicion is that perhaps it has something to do with the changesets cli update 2.7.2 --> 2.8.0 , please let me know if you would like more info for diagnosing what's going wrong.
