### ISSUE TITLE
pnpm lock file update

### ISSUE THREAD

**Issue by ianwalter** [atlassian/changesets#421]
## Affected Packages

Not sure.

## Problem

When using pnpm with changesets in a monorepo, after merging the "Update Versions" PR from the changesets action, CI breaks on the "Install" step since changesets has updated the versions in linked packages but has not updated the `pnpm-lock.yaml`. 

## Proposed solution

I think after changesets updates linked package versions to the new/upcoming version, it should run `pnpm install -r` (recursive) to update the lock file. Not sure if there is a better solution or how pnpm itself is handling this issue. Thoughts @zkochan ?

**Comment by zkochan** [comment]
Yes, currently I manually run `pnpm install` after running `changesets version`.

**Comment by Andarist** [comment]
@zkochan Ideally changesets would "just work" in a variety of scenarios (including this one). What would be your recommendation here? Should we update `pnpm-lock.yaml` "manually" at the end of the version script?

**Comment by zkochan** [comment]
I don't think updating it manuall is a good solution. What if we change the format of the lockfile in the future? I'd recommend running `pnpm install --lockfile-only` after `changesets version`.

**Comment by Andarist** [comment]
Sounds good, I've marked this issue as a good first issue - hopefully, someone will jump into working on this soon-ish.

**Comment by ianwalter** [comment]
Thank you, I can probably submit a PR after my other issue/PR is resolved.

**Comment by mskelton** [comment]
A similar issue to this occurs with Yarn 2 as it also stores the versions of dependent packages in the lockfile.  Yarn 1 did not store the versions of dependent packages in the lockfile, but Yarn 2 appears to have changed that behavior.  Would that fit in the scope of this as well or should a separate issue be opened for that?

**Comment by Andarist** [comment]
@mskelton a separate one would probably make sense - just please link to this one when you report it.

**Comment by jedrichards** [comment]
Just making a note regarding Yarn Berry behaviour, maybe of interest or help with Googling this issue for others ... commonly on CI we run `yarn install --immutable` but this will fail on the Version Packages PR since that has amended the dependency versions without updating the lockfile and outputs the following failure:

```
The lockfile would have been modified by this install, which is explicitly forbidden.
```

**Comment by equinusocio** [comment]
This is an issue even by running changeset manually with npm, after the versioning and publishing the lock should be updated automatically to update the package version. Right now we have to run `npm i` every time we do a release.

This is because many automation systems rely on the package-lock changes to use the cache or not, so if they don't see any changes in the lockfile they just use the previous install cache, using in fact the previous publishing version of the package.

**Comment by Andarist** [comment]
@equinusocio I totally agree - I've been checking with npm a few weeks back and... they don't even update the lockfile when running `npm --workspace [w] version [v]`  ([bug report](https://github.com/npm/cli/issues/3756)).

So I guess that our best option would be to update those lockfiles manually. We'd have to understand how each format of the lockfiles works to do this effectively. 

PRs would be appreciated to solve this as I'm pretty busy lately.

**Comment by dagda1** [comment]
A work around for yarn is to set `YARN_ENABLE_IMMUTABLE_INSTALLS` to false

e.g.

```yml
      - name: Install Dependencies
        run: yarn
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
```

**Comment by dagda1** [comment]
This is a workaround for yarn 3

```yml
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
```

What would the correct sequence of steps be to fix this?

**Comment by mskelton** [comment]
@dagda1 Disabling immutable installs is generally not a good idea as it removes an important safety measure provided by lockfiles which is ensuring your builds always behave the same until you change the lockfile.  If you disable it and then say manually update a package in your package.json file without running `yarn`, your local testing may not pick up any bugs but then when you push your branch, Yarn will update the lockfile with the new dependency and produce a different state than you were testing with locally.

At the moment the best workaround is to run `yarn` as part of the version step to update the versions stored in the lockfile of the packages you are publishing.

**Comment by equinusocio** [comment]
On our side, we ended up using a custom sh script:

```yml
      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: ./update-lock.sh
          publish: npm run release
          commit: "ci: release"
          title: "ci: release"
```

``sh
npx changeset version
npm i --package-lock-only
```

**Comment by dagda1** [comment]
@mskelton @equinusocio thank you, I was not aware of `npm i --package-lock-only` or the yarn equivalent `yarn install --mode update-lockfile`

**Comment by klippx** [comment]
@zkochan 
> Yes, currently I manually run pnpm install after running changesets version.

Sure, this works if you manually run `changeset version` but if you use the github action:
```
      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Then that opens a PR _without_ updating `pnpm-lock.yaml` which I think was the issue that OP started here?

The action is great but it is lacking that small piece. I love the action but do I manually have to jump into each one of it's PRs and do this step manually, is this the best solution?

Can we at least have an input parameter to the action where we opt-in to the behaviour of also running `pnpm install` and commiting the changes to `pnpm-lock.yaml` ? If so, the github action would be perfect. <3

**Comment by stefcameron** [comment]
This is an ongoing problem with NPM `package-lock.json` files as well, and has been for a long time now. Quite annoying to end-up with an outdated lock file that gets modified locally later on when running `npm install` by anyone using the repo. This _was_ part of what Changesets did, but the behavior changed a while ago, which re-introduces a manual step into what should be automated.

**Comment by oe-josh-martin** [comment]
We've managed to resolve this by adding a new workflow action set to `on: workflow_dispatch` that installs the packages installs the packages with `--no-prefer-frozen-lockfile` and then commits with `stefanzweifel/git-auto-commit-action@v4`

```
on:
  workflow_dispatch:

- name: Install dependencies with pnpm
   run: |
       pnpm install --no-prefer-frozen-lockfile

- uses: stefanzweifel/git-auto-commit-action@v4
   with:
       commit_message: 'chore(release): update lockfile'
```

then in our release action after the changeset step dispatch this workflow with `benc-uk/workflow-dispatch@v1`

```
- name: Dispatch lockfile event
   continue-on-error: true
   uses: benc-uk/workflow-dispatch@v1
   with:
      workflow: update-lock.yml
      ref: refs/heads/changeset-release/main
```

**Comment by openscript** [comment]
I've updated my workflow to this and it's not an issue ever since:

```yaml
name: Version packages

on:
  push:
    branches:
      - main

jobs:
  version-packages:
    name: Version packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          commit: "chore: publish new release"
          title: "chore: publish new release"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Update lock file
        run: pnpm install --lockfile-only

      - name: Commit lock file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update lock file"
          branch: changeset-release/main
```

**Comment by o-az** [comment]
> ```yaml
> Get current branch
> ```

@openscript what is the purpose of the `"Get current branch"` step since your action only runs in `main`? Wouldn't the value always be `main`?

**Comment by openscript** [comment]
> > ```yaml
> > Get current branch
> > ```
> 
> @openscript what is the purpose of the `"Get current branch"` step since your action only runs in `main`? Wouldn't the value always be `main`?

@o-az In the step before changesets changes the branch sometimes to it's own working branch and updates versions in package.json files, which brings lock files out of sync.

**Comment by scottquested** [comment]
None of the solutions I found here or online seemed to work, so thought I would post the solution we came up with for anyone still struggling. Took inspiration from @openscript's solution, but we needed to trigger other workflows after.

We used the standard `GITHUB_TOKEN` for the changesets PR and then a `GITHUB_PAT` for updating the lockfile, which then triggers any subsequent workflows (a PR check (lint, build etc) in our case). 

```yml
#changesets.yml

name: Create Release Pull Request

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create-release:
    name: Create Release Pull Request
    runs-on: [ ... ]
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: pnpm setup
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: "ci: release"
          title: "ci: release"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-lock:
    needs: create-release
    name: Update pnpm lock file
    runs-on: [ ... ]
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'changeset-release/master'
          token: ${{ secrets.GITHUB_PAT }}
          fetch-depth: 0

      - name: pnpm setup
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
  
      - name: Update lock file
        run: pnpm install --lockfile-only
  
      - name: Commit lock file
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d
        with:
          commit_message: "chore: pnpm.lock"
          branch: changeset-release/master

```
